name: Development Build

on:
  push:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get Release Version
      id: getReleaseVersion
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/v}

    - name: Get Release Version
      id: getReleaseVersion-new
      run: echo tag=${GITHUB_REF#refs/*/v} >> $GITHUB_OUTPUT

    - name: Echo version
      run: echo ${{ steps.getReleaseVersion.outputs.tag }}

    - name: Echo version
      run: echo ${{ steps.getReleaseVersion-new.outputs.tag }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal