name: Release Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Package Nuget
      run: dotnet pack -p:PackageVersion=0.0.${{ github.run_number }} -o ./output

    # - name: Push Nuget Package
    #   run: dotnet nuget push ./output/TinyHealthCheck.0.0.${{ github.run_number }}.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
    #   if: github.ref == 'refs/heads/main'

    ## Checkout so we can apply the new tag
    - uses: actions/checkout@v2
      with:
        fetch-depth: "0"

    ## Documentation: https://github.com/marvinpinto/action-automatic-releases
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false